"""corrijo base de datos

Revision ID: 070d90e01203
Revises: a51efda388fb
Create Date: 2024-07-25 15:50:31.923980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '070d90e01203'
down_revision = 'a51efda388fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
