"""agrego modelos gamma y SO

Revision ID: 081a4aa0fda1
Revises: b074d8e5244d
Create Date: 2024-07-27 19:22:44.786930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081a4aa0fda1'
down_revision = 'b074d8e5244d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sistema_operativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gama_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sistema_operativo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sistema_operativo', ['sistema_operativo_id'], ['id'])
        batch_op.create_foreign_key(None, 'gama', ['gama_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sistema_operativo_id')
        batch_op.drop_column('gama_id')

    op.drop_table('sistema_operativo')
    op.drop_table('gama')
    # ### end Alembic commands ###
