"""creacion de modelo

Revision ID: 155aef45e869
Revises: 79bc560e41a7
Create Date: 2024-08-06 22:13:04.821565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155aef45e869'
down_revision = '79bc560e41a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelo')
    # ### end Alembic commands ###
