"""agrego especificacioneses como relacion con celular

Revision ID: 20b8dfecb615
Revises: 2024987ac2e2
Create Date: 2024-08-07 11:04:01.510170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b8dfecb615'
down_revision = '2024987ac2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especificacion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'especificacion', ['especificacion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('especificacion_id')

    # ### end Alembic commands ###
