"""empty message

Revision ID: 3f0bf89c1dd0
Revises: 37a0e9da7874
Create Date: 2024-07-19 14:03:35.614878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0bf89c1dd0'
down_revision = '37a0e9da7874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
