"""otros modelos

Revision ID: 495280fe83d9
Revises: f9d41e23946e
Create Date: 2024-10-23 12:06:34.507915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495280fe83d9'
down_revision = 'f9d41e23946e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('almacenamiento', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabricante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('localidad', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sistema_operativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('localidad', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.Column('fabricante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fabricante_id'], ['fabricante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('especificacion_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('gama_id', sa.Integer(), nullable=True),
    sa.Column('sistema_operativo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['especificacion_id'], ['especificacion.id'], ),
    sa.ForeignKeyConstraint(['gama_id'], ['gama.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['sistema_operativo_id'], ['sistema_operativo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celular')
    op.drop_table('proveedor')
    op.drop_table('modelo')
    op.drop_table('sistema_operativo')
    op.drop_table('marca')
    op.drop_table('gama')
    op.drop_table('fabricante')
    op.drop_table('especificacion')
    op.drop_table('categoria')
    # ### end Alembic commands ###
