"""empty message

Revision ID: 4b53de6dddbc
Revises: 6b651b9dbfb1
Create Date: 2024-07-26 10:55:51.261139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b53de6dddbc'
down_revision = '6b651b9dbfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.alter_column('contacto',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('contacto',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('contacto',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.alter_column('contacto',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
