"""elimino foreign keys redundantes

Revision ID: 51cd14788c3c
Revises: aa3dd915825b
Create Date: 2024-07-25 17:20:44.172646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51cd14788c3c'
down_revision = 'aa3dd915825b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_constraint('accesorio_ibfk_1', type_='foreignkey')
        batch_op.drop_column('celular_id')

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.drop_constraint('fabricante_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('fabricante_ibfk_2', type_='foreignkey')
        batch_op.drop_column('proveedor_id')
        batch_op.drop_column('marca_id')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint('modelo_ibfk_2', type_='foreignkey')
        batch_op.drop_column('celular_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('modelo_ibfk_2', 'celular', ['celular_id'], ['id'])

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('proveedor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fabricante_ibfk_2', 'marca', ['marca_id'], ['id'])
        batch_op.create_foreign_key('fabricante_ibfk_1', 'proveedor', ['proveedor_id'], ['id'])

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('accesorio_ibfk_1', 'celular', ['celular_id'], ['id'])

    # ### end Alembic commands ###
