"""prueba

Revision ID: 6223b8122739
Revises: 4a6ec11e50e8
Create Date: 2024-07-18 22:54:37.491401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6223b8122739'
down_revision = '4a6ec11e50e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_constraint('celular_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('celular_ibfk_2', type_='foreignkey')
        batch_op.drop_column('accesorios_id')
        batch_op.drop_column('stock')
        batch_op.drop_column('usado')
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('usado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('accesorios_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('celular_ibfk_2', 'categoria', ['categoria_id'], ['id'])
        batch_op.create_foreign_key('celular_ibfk_1', 'accesorios', ['accesorios_id'], ['id'])

    # ### end Alembic commands ###
