"""empty message

Revision ID: 68b2d3514928
Revises: 4b53de6dddbc
Create Date: 2024-07-26 11:06:56.692458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b2d3514928'
down_revision = '4b53de6dddbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabricante_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fabricante', ['fabricante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fabricante_id')

    # ### end Alembic commands ###
