<<<<<<<< HEAD:migrations/versions/6b651b9dbfb1_primer_migrate.py
"""primer migrate

Revision ID: 6b651b9dbfb1
Revises: 
Create Date: 2024-07-25 21:57:25.997445
========
"""corrijo y elimino relaciones

Revision ID: a51efda388fb
Revises: 
Create Date: 2024-07-16 12:21:33.146859
>>>>>>>> master:migrations/versions/a51efda388fb_corrijo_y_elimino_relaciones.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/6b651b9dbfb1_primer_migrate.py
revision = '6b651b9dbfb1'
========
revision = 'a51efda388fb'
>>>>>>>> master:migrations/versions/a51efda388fb_corrijo_y_elimino_relaciones.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('compatibilidad', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('almacenamiento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabricante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('contacto', sa.Integer(), nullable=False),
    sa.Column('localidad', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('contacto', sa.Integer(), nullable=False),
    sa.Column('localidad', sa.String(length=50), nullable=False),
    sa.Column('fabricante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fabricante_id'], ['fabricante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fabricante_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fabricante_id'], ['fabricante.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celular_accesorio',
    sa.Column('celular_id', sa.Integer(), nullable=False),
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accesorio_id'], ['accesorio.id'], ),
    sa.ForeignKeyConstraint(['celular_id'], ['celular.id'], ),
    sa.PrimaryKeyConstraint('celular_id', 'accesorio_id')
    )
    op.create_table('celular_especificacion',
    sa.Column('celular_id', sa.Integer(), nullable=False),
    sa.Column('especificacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celular_id'], ['celular.id'], ),
    sa.ForeignKeyConstraint(['especificacion_id'], ['especificacion.id'], ),
    sa.PrimaryKeyConstraint('celular_id', 'especificacion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celular_especificacion')
    op.drop_table('celular_accesorio')
    op.drop_table('celular')
    op.drop_table('modelo')
    op.drop_table('marca')
    op.drop_table('proveedor')
    op.drop_table('fabricante')
    op.drop_table('especificacion')
    op.drop_table('categoria')
    op.drop_table('accesorio')
    # ### end Alembic commands ###
