"""Agrego fabricantes y proveedoreres

Revision ID: 842826c0c993
Revises: 155aef45e869
Create Date: 2024-08-06 22:35:36.869118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842826c0c993'
down_revision = '155aef45e869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabricante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('localidad', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('localidad', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.Column('fabricante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fabricante_id'], ['fabricante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    op.drop_table('fabricante')
    # ### end Alembic commands ###
