"""agrego las relaciones e id's faltantes

Revision ID: aa3dd915825b
Revises: 070d90e01203
Create Date: 2024-07-25 17:01:49.049910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3dd915825b'
down_revision = '070d90e01203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'celular', ['celular_id'], ['id'])

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proveedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proveedor', ['proveedor_id'], ['id'])
        batch_op.create_foreign_key(None, 'marca', ['marca_id'], ['id'])

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'celular', ['celular_id'], ['id'])

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'marca', ['marca_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('marca_id')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('celular_id')

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proveedor_id')
        batch_op.drop_column('marca_id')

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('celular_id')

    # ### end Alembic commands ###
