"""empty message

Revision ID: f43f3b3e48fc
Revises: 95a5466eb97e
Create Date: 2024-07-12 14:44:59.224079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43f3b3e48fc'
down_revision = '95a5466eb97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
